name: Backend Test CI

on:
  workflow_dispatch:
  push:
    branches: ["release"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["release"]
    paths:
      - "backend/**"

env:
  NODE_ENV: TEST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        working-directory: ./backend/
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
        
      - name: Install Dependencies
        working-directory: ./backend/
        run: npm ci

      - name: Run Tests
        working-directory: ./backend/
        run: npm run test
